In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("income.csv")
df.head()

   id  age  income  occupation  years of experience
0   1   64   35397   developer                   10
1   2   54   32943     teacher                    3
2   3   43   21947   professor                    9
3   4   21   37092    engineer                    5
4   5   64   35935  accountant                   10

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   50 non-null     int64
 1   age                  50 non-null     int64
 2   income               50 non-null     int64
 3   occupation           50 non-null     object
 4   years of experience  50 non-null     int64
dtypes: int64(4), object(1)
memory usage: 2.1+ KB

In [4]:
df.describe()

             id        age        income  years of experience
count  50.00000  50.000000     50.000000             50.00000
mean   25.50000  43.140000  29590.160000              9.22000
std    14.57738  12.917335   6164.559992              5.96346
min     1.00000  20.000000  20465.000000              0.00000
25%    13.25000  34.500000  23938.000000              4.25000
50%    25.50000  43.000000  29158.000000              9.50000
75%    37.75000  53.000000  35377.750000             13.75000
max    50.00000  65.000000  39369.000000             20.00000

In [5]:
df.isna().sum()

id                     0
age                    0
income                 0
occupation             0
years of experience    0
dtype: int64

In [6]:
categorical_col = "age"
numerical_col = "income"

In [7]:
summary_stats = df.groupby(categorical_col)[numerical_col].agg(
    mean="mean",
    median="median",
    min="min",
    max="max",
    std="std"
)

summary_stats

         mean   median    min    max           std
age
20   26907.50  26907.5  21214  32601   8051.824917
21   37092.00  37092.0  37092  37092           NaN
24   37021.00  37021.0  37021  37021           NaN
26   31247.00  32388.5  23520  36691   6031.503240
27   33222.00  33222.0  33222  33222           NaN
30   26865.00  26865.0  26865  26865           NaN
32   32283.00  32283.0  32283  32283           NaN
33   29918.00  29918.0  29918  29918           NaN
34   23712.00  23712.0  23712  23712           NaN
36   31222.50  31222.5  23926  38519  10318.809258
37   29185.00  28859.0  22040  36656   7313.451374
38   28751.00  28751.0  28751  28751           NaN
39   21239.00  21239.0  21239  21239           NaN
40   24969.00  24969.0  22165  27773   3965.454829
43   30572.75  31207.5  21947  37929   6617.504685
44   34992.00  34992.0  34992  34992           NaN
45   31371.00  31371.0  26067  36675   7500.988735
46   23039.00  23039.0  21063  25015   2794.485999
47   23134.00  23134.0  21012  25256   3000.961179
50   23974.00  23974.0  23974  23974           NaN
51   30667.00  30667.0  30667  30667           NaN
52   38933.00  38933.0  38933  38933           NaN
53   32841.50  32841.5  28486  37197   6159.607171
54   29637.50  29637.5  26332  32943   4674.682930
57   20762.00  20762.0  20762  20762           NaN
58   31000.00  31000.0  26798  35202   5942.525389
59   39369.00  39369.0  39369  39369           NaN
62   23964.50  23964.5  20494  27435   4908.028168
64   30599.00  35397.0  20465  35935   8780.422997
65   37904.00  37904.0  37904  37904           NaN

In [8]:
grouped_values = df.groupby(categorical_col)[numerical_col].apply(list)

grouped_values

age
20                  [32601, 21214]
21                         [37092]
24                         [37021]
26    [36691, 29457, 35320, 23520]
27                         [33222]
30                         [26865]
32                         [32283]
33                         [29918]
34                         [23712]
36                  [23926, 38519]
37           [22040, 36656, 28859]
38                         [28751]
39                         [21239]
40                  [27773, 22165]
43    [21947, 32220, 30195, 37929]
44                         [34992]
45                  [26067, 36675]
46                  [21063, 25015]
47                  [25256, 21012]
50                         [23974]
51                         [30667]
52                         [38933]
53                  [28486, 37197]
54                  [32943, 26332]
57                         [20762]
58                  [35202, 26798]
59                         [39369]
62                  [20494, 27435]
64           [35397, 35935, 20465]
65                         [37904]
Name: income, dtype: object

In [9]:
summary_stats = df.groupby(categorical_col)[numerical_col].agg(
    mean="mean",
    median="median",
    min="min",
    max="max",
    std="std"
)

summary_stats

         mean   median    min    max           std
age
20   26907.50  26907.5  21214  32601   8051.824917
21   37092.00  37092.0  37092  37092           NaN
24   37021.00  37021.0  37021  37021           NaN
26   31247.00  32388.5  23520  36691   6031.503240
27   33222.00  33222.0  33222  33222           NaN
30   26865.00  26865.0  26865  26865           NaN
32   32283.00  32283.0  32283  32283           NaN
33   29918.00  29918.0  29918  29918           NaN
34   23712.00  23712.0  23712  23712           NaN
36   31222.50  31222.5  23926  38519  10318.809258
37   29185.00  28859.0  22040  36656   7313.451374
38   28751.00  28751.0  28751  28751           NaN
39   21239.00  21239.0  21239  21239           NaN
40   24969.00  24969.0  22165  27773   3965.454829
43   30572.75  31207.5  21947  37929   6617.504685
44   34992.00  34992.0  34992  34992           NaN
45   31371.00  31371.0  26067  36675   7500.988735
46   23039.00  23039.0  21063  25015   2794.485999
47   23134.00  23134.0  21012  25256   3000.961179
50   23974.00  23974.0  23974  23974           NaN
51   30667.00  30667.0  30667  30667           NaN
52   38933.00  38933.0  38933  38933           NaN
53   32841.50  32841.5  28486  37197   6159.607171
54   29637.50  29637.5  26332  32943   4674.682930
57   20762.00  20762.0  20762  20762           NaN
58   31000.00  31000.0  26798  35202   5942.525389
59   39369.00  39369.0  39369  39369           NaN
62   23964.50  23964.5  20494  27435   4908.028168
64   30599.00  35397.0  20465  35935   8780.422997
65   37904.00  37904.0  37904  37904           NaN

In [10]:
print("Summary Statistics:\n", summary_stats)
print("\nGrouped Values:\n", grouped_values)

Summary Statistics:
          mean   median    min    max           std
age
20   26907.50  26907.5  21214  32601   8051.824917
21   37092.00  37092.0  37092  37092           NaN
24   37021.00  37021.0  37021  37021           NaN
26   31247.00  32388.5  23520  36691   6031.503240
27   33222.00  33222.0  33222  33222           NaN
30   26865.00  26865.0  26865  26865           NaN
32   32283.00  32283.0  32283  32283           NaN
33   29918.00  29918.0  29918  29918           NaN
34   23712.00  23712.0  23712  23712           NaN
36   31222.50  31222.5  23926  38519  10318.809258
37   29185.00  28859.0  22040  36656   7313.451374
38   28751.00  28751.0  28751  28751           NaN
39   21239.00  21239.0  21239  21239           NaN
40   24969.00  24969.0  22165  27773   3965.454829
43   30572.75  31207.5  21947  37929   6617.504685
44   34992.00  34992.0  34992  34992           NaN
45   31371.00  31371.0  26067  36675   7500.988735
46   23039.00  23039.0  21063  25015   2794.485999
47   23134.00  23134.0  21012  25256   3000.961179
50   23974.00  23974.0  23974  23974           NaN
51   30667.00  30667.0  30667  30667           NaN
52   38933.00  38933.0  38933  38933           NaN
53   32841.50  32841.5  28486  37197   6159.607171
54   29637.50  29637.5  26332  32943   4674.682930
57   20762.00  20762.0  20762  20762           NaN
58   31000.00  31000.0  26798  35202   5942.525389
59   39369.00  39369.0  39369  39369           NaN
62   23964.50  23964.5  20494  27435   4908.028168
64   30599.00  35397.0  20465  35935   8780.422997
65   37904.00  37904.0  37904  37904           NaN

Grouped Values:
 age
20                  [32601, 21214]
21                         [37092]
24                         [37021]
26    [36691, 29457, 35320, 23520]
27                         [33222]
30                         [26865]
32                         [32283]
33                         [29918]
34                         [23712]
36                  [23926, 38519]
37           [22040, 36656, 28859]
38                         [28751]
39                         [21239]
40                  [27773, 22165]
43    [21947, 32220, 30195, 37929]
44                         [34992]
45                  [26067, 36675]
46                  [21063, 25015]
47                  [25256, 21012]
50                         [23974]
51                         [30667]
52                         [38933]
53                  [28486, 37197]
54                  [32943, 26332]
57                         [20762]
58                  [35202, 26798]
59                         [39369]
62                  [20494, 27435]
64           [35397, 35935, 20465]
65                         [37904]
Name: income, dtype: object